### ISSUE TITLE
3.15.6 - error compiling pcm512 sound drivers

### ISSUE THREAD

**Issue by ha5di** [raspberrypi/linux#641]
Compiling 3.15.6 kernel it fails to build pcm512 codecs and kernel itself.. Disabling them kernel build OK. Error messages:

---

  err = snd_card_create(index[dev], id[dev], THIS_MODULE, 0, &g_card);
  ^
sound/arm/bcm2835-pcm.c: In function 'snd_bcm2835_playback_close':
sound/arm/bcm2835-pcm.c:218:2: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  bcm2835_chip_t *chip = snd_pcm_substream_chip(substream);
  ^
sound/arm/bcm2835-pcm.c:224:2: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  struct snd_pcm_runtime *runtime = substream->runtime;
  ^
sound/soc/codecs/pcm512x-i2c.c: In function 'pcm512x_i2c_probe':
sound/soc/codecs/pcm512x-i2c.c:28:2: error: implicit declaration of function 'devm_regmap_init_i2c' [-Werror=implicit-fu
nction-declaration]
  regmap = devm_regmap_init_i2c(i2c, &pcm512x_regmap);
  ^
sound/soc/codecs/pcm512x-i2c.c:28:38: error: 'pcm512x_regmap' undeclared (first use in this function)
  regmap = devm_regmap_init_i2c(i2c, &pcm512x_regmap);
                                      ^
sound/soc/codecs/pcm512x-i2c.c:28:38: note: each undeclared identifier is reported only once for each function it appear
s in
sound/soc/codecs/pcm512x-i2c.c:32:2: error: implicit declaration of function 'pcm512x_probe' [-Werror=implicit-function-
declaration]
  return pcm512x_probe(&i2c->dev, regmap);
  ^
sound/soc/codecs/pcm512x-i2c.c: In function 'pcm512x_i2c_remove':
sound/soc/codecs/pcm512x-i2c.c:37:2: error: implicit declaration of function 'pcm512x_remove' [-Werror=implicit-function
-declaration]
  pcm512x_remove(&i2c->dev);
  ^
sound/soc/codecs/pcm512x-i2c.c: At top level:
sound/soc/codecs/pcm512x-i2c.c:63:14: error: 'pcm512x_pm_ops' undeclared here (not in a function)
   .pm     = &pcm512x_pm_ops,
              ^
cc1: some warnings being treated as errors

---

**Comment by notro** [comment]
It seems this commit:
[Add IQaudIO Sound Card support for Raspberry Pi](https://github.com/raspberrypi/linux/commit/dfa4d76b94b9005d15f6ae6b43a3ba9eadb4d954#diff-b566f93f0d9f8b6f7d03d5f52f98c652L96)
was based such that this commit was not in place:
[ASoC: pcm512x: Split out bus drivers](https://github.com/raspberrypi/linux/commit/22066226b50e40591d67aef1d5525abce7515df2)

**Comment by popcornmix** [comment]
@iqaudio can you have a look into this?

**Comment by iqaudio** [comment]
I am not aware of any changes to the pcm512x driver to split out i2c and spi. 
3.14 retains the single driver, I don't know what MarkB's plans were with the driver but suggest 3.15 retains 3.14 code base until that's resolved.

**Comment by popcornmix** [comment]
I'm afraid trying to revert a section of the 3.15 kernel (that I have no knowledge of) to 3.14 is not something I'm happy doing.

I'm willing to accept a PR that makes the iqaudio patches work with 3.15, or I can drop the iqaudio patches that cause build errors on 3.15 (and future) kernels trees.

Ideally any patches we are using should be pushed upstream to avoid breakages like this.

**Comment by ha5di** [comment]
Current 3.5.18 builds fine, issue can be closed.
