### ISSUE TITLE
Matching firmware for 3.6.y

### ISSUE THREAD

**Issue by CurlyMoo** [raspberrypi/linux#157]
I've compiled the new 3.6.y. Works perfectly!

However, the firmware doesn't seem te match the kernel version.
I get the following error when i try to run this command:

```
 /opt/vc/bin/vcgencmd
VCHI initialization failed
```

I've tried to update the firmware by using:

```
SKIP_KERNEL=1 rpi_update
```

or with

```
git pull --depth 5 https://github.com/raspberrypi/firmware.git
#etc.
```

But none of this steps worked.

How can i install the correct firmware for kernel 3.6.y?

**Comment by popcornmix** [comment]
The 3.6.y branch is experimental. This is closest firmware:
https://github.com/Hexxeh/rpi-firmware/commit/f8b144bbebeeae4f87a6207c346faeece1d004f6
but it's not that stable.

Replacing drivers/misc/vc04_services with the one from 3.2.27 may be better solution for now - then you can use official firmware.

**Comment by CurlyMoo** [comment]
To make this clear.
Option 1:
Pull the firmware from Hexxeh's git and checkout f8b144bbebeeae4f87a6207c346faeece1d004f6

Option 2:
Install the latest firmware from Hexxeh's git and replace the drivers/misc/vc04_services with the 3.2.27 ones?

**Comment by popcornmix** [comment]
1:
`sudo 'rpi-update f8b144bbebeeae4f87a6207c346faeece1d004f6`
2:
Replace drivers/misc/vc04_services of branch rpi-3.6.y from this source repo with the code from rpi-3.2.27.
Then rebuild your kernel.

**Comment by CurlyMoo** [comment]
Kernel 3.6.y is not compiling with the vc04_services from rpi-3.2.27. All kinds of errors show up.

**Comment by CurlyMoo** [comment]
I've managed to fixed it by also replacing the sound/arm by the one from 3.2.27

Thanks!

**Comment by zette** [comment]
Hi,
I'm also trying to make pi run with 3.6.y. I replaced 3.6.y source drivers/misc/vc04_services and sound/arm with the 3.2.27, but still get blocking errors:
  CC      drivers/misc/vc04_services/interface/vchiq_arm/vchiq_2835_arm.o
drivers/misc/vc04_services/interface/vchiq_arm/vchiq_2835_arm.c: In function 'vchiq_platform_init':
drivers/misc/vc04_services/interface/vchiq_arm/vchiq_2835_arm.c:129:3: error: 'IRQF_SAMPLE_RANDOM' undeclared (first use in this function)
drivers/misc/vc04_services/interface/vchiq_arm/vchiq_2835_arm.c:129:3: note: each undeclared identifier is reported only once for each function it appears in

Any idea what can be wrong? I'm using same config as for original 3.6.y build.

**Comment by popcornmix** [comment]
I've just committed firmware and kernel for 3.6.y. You can get it from:
https://github.com/raspberrypi/firmware/tree/next
or
https://github.com/Hexxeh/rpi-firmware/tree/next

I believe this combination has vchiq bugs fixed, and should be stable (although needs testing).
You can upgrade to it with:

```
sudo rpi-update 0e358b3082a611975a7d467f457e8769b8d88663
```

**Comment by CurlyMoo** [comment]
XBian also runs on 3.6.1 sinds i got it to work. A tutorial can we find in our Docs sections on our git.

**Comment by zette** [comment]
Some good and some bad news. I managed to build and run 3.6.6 with new firmware as suggested. System boot fine to  console without errors/warnings.
Unfortunately xmbc does not start. I have one error for audio (probably harmless), and other for egl:
-EGL failed to set HDMI mode (2,2,56)=1
-EGL error in CreateSurfance: 300b

and following restart of procedure with creation of fresh Native Window wich also fais with same error.

I'm using raspbmc nightly xbmc build (working with 3.2.27), and 128/128 split. Any ideas?

PS: installing same kernel with latest vc with hardfp on xbian 1.0a2 gives me xbmc, but with wrong screen clock rate (wrong scale, awkward positioning, not usable, etc...). I bet firmware needs some more tweaks before moving on. I'll test it also on my TV, maybe get better results.

**Comment by popcornmix** [comment]
I think xbmc might need relinking with the updated libraries.
I've had confirmation that OpenELEC works and there will be a test build based on this firmware soon.

**Comment by farnz** [comment]
Is the [raspberrypi/userland](https://github.com/raspberrypi/userland) repository going to be updated with new sources for this version of VCHIQ? It currently understands VCHIQ version 2, while this firmware needs VCHIQ version 3 (or higher).

Edit to add: I've just pulled in a next branch, created overnight. Thanks.

**Comment by popcornmix** [comment]
I believe this issue is reolved. Please reopen if there are still problems.
