### ISSUE TITLE
rpi-4.8.y build failure

### ISSUE THREAD

**Issue by asavah** [raspberrypi/linux#1671]
rpi-4.8.y branch fails to build with (cross)gcc-6.2
config is unmodified bcm2709_defconfig

```
drivers/media/platform/bcm2835/bcm2835-camera.c:656:17: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .queue_setup = queue_setup,
                 ^~~~~~~~~~~
drivers/media/platform/bcm2835/bcm2835-camera.c:656:17: note: (near initialization for ‘bm2835_mmal_video_qops.queue_setup’)
```

**Comment by popcornmix** [comment]
Try grabbing https://github.com/raspberrypi/linux/pull/1667/commits/6573f071ef1f347a83e0853df95e7837fabdfe44

**Comment by asavah** [comment]
Thx, will rebuild in a few mins, from the looks if it - this should work,
with my limited kernel knowledge I've already traced the upstream change to https://github.com/raspberrypi/linux/commit/36c0f8b32c4bd4f668cedfba6d97afaa84f055fb

Will report back asap.

**Comment by asavah** [comment]
@popcornmix The suggested fix works like a charm.
Clean build with defconfig. Thx.
Feel free to close once/if you merge the fix.

**Comment by asavah** [comment]
Fixed in https://github.com/raspberrypi/linux/commit/88403aeb5009ffa3cf172bfaa06087ee2ee3cabe
